<?php

use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;

/**
 * @file
 * Module file for User registration.
 */

/**
 * Implements hook_preprocess_page().
 */
function user_import_preprocess_page(&$variables) {
  $variables['page']['#cache']['contexts'][] = 'route';
  $urlRoute = \Drupal::routeMatch()->getRouteName();
  if (($urlRoute == 'user_import.admin_settings')) {
    $variables['#attached']['library'][] = 'user_import/common-styling';
  }
  if (($urlRoute == 'user_import.multistep_two')) {
    $variables['#attached']['library'][] = 'user_import/common-styling';
  }
}


/**
 * Implements hook_mail().
 */
function user_import_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'create_user':

      $system_site_config = \Drupal::config('system.site');
      $message['from'] = $system_site_config->get('mail');
      
      if(!empty($params['message_subject'])){
        $message['subject'] = t($params['message_subject'], $options);
      }else{
        $message['subject'] = t('@[site:name]', array('@[site:name]' => $params['[site:name]']), $options);
      }

      if($params['email_format'] == 0){
        $message['body'][] = Html::normalize($params['message']);
      }else{
        $message['body'][] = Html::normalize($params['message']);
      }
      break;
  }
}
